name: deploy-static

on:
  push:
    branches: [dev]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.STATIC_BUILD_ENABLED }} == 'true' ]; then
            echo "ok=enabled" >> $GITHUB_OUTPUT
          fi
  deploy-static:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled'}}
    environment:
      name: '${{ github.event.repository.name }}-static-build-gh-pages'
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infinite Reality Engine
        uses: actions/checkout@v3
        with:
          repository: ir-engine/ir-engine
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: './packages/projects/projects/${{ github.event.org.id }}/${{ github.event.repository.name }}'
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: restore lerna
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
            package-lock.json
          key: ${{ runner.os }}-branch-build-${{ hashFiles('**/package.json') }}
      - run: cp .env.local.default .env.local
      - run: npm install --production=false --loglevel notice --legacy-peer-deps
      - run: cd './packages/projects/projects/${{ github.event.org.id }}/${{ github.event.repository.name }}' && npx cross-env STATIC_BUILD_HOST=${{ secrets.STATIC_BUILD_HOST }} npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './packages/projects/projects/${{ github.event.org.id }}/${{ github.event.repository.name }}/dist'
      - name: Sleep for 15 seconds
        run: sleep 15s
        shell: bash
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
